package com.aspire.java.Exception;

public class TRy
{
 public static void main(String[] args) 
 {
	int a=10;
	int b=0;
	int div;
	
	 
	 try
	 {
		 div=a/b;
		 System.out.println(div); 
	 }
	 catch(ArithmeticException e)
	 {
		 System.out.println("do not divide with zero");
	 }
	 
	 
	 
	 
	 
	 
	 
 }
	
	
	
	
	
	
	
	
	
	
	
	
	
}
